apiVersion: v1
appVersion: 2.2.1
description: An open source trusted cloud native registry that stores, signs, and
  scans content
engine: gotpl
home: https://github.com/tmax-cloud
icon: https://raw.githubusercontent.com/goharbor/website/master/static/img/logos/harbor-icon-color.png
keywords:
- docker
- registry
- harbor
maintainers:
- email: yinw@vmware.com
  name: Wenkai Yin
- email: hweiwei@vmware.com
  name: Weiwei He
- email: dengq@vmware.com
  name: Qian Deng
name: HyperRegistry
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
version: 5.0.0
